### PR TITLE
Update to Slint 1.7.1

### PR DESCRIPTION
**Pull request by tronical**

### CODE REVIEW

**Comment by microhobby** [comment]
Thanks @tronical ! Sorry for the delay, I was in vacations, I'm back now!

**Comment by tronical** [comment]
Thanks :)

**Comment by tronical** [comment]
I notice that the commontorizon/slint-sdk-* containers have been updated (https://hub.docker.com/r/commontorizon/slint-sdk-amd64/tags), but commontorizon/slint-base/* not yet (https://hub.docker.com/r/commontorizon/slint-base-arm64/tags). Is there something missing in this PR that should have triggered the rebuild?

**Comment by microhobby** [comment]
@tronical sorry about that, we had an out-of-storage issue on the server. I retriggered the build now, should be updated soon. Thanks to notify.

**Comment by tronical** [comment]
Thanks for fixing this. I've made the corresponding PR https://github.com/toradex/vscode-torizon-templates/pull/219 to propagate it all the way :)

**Pull request merged**
